app = "invest-report"
primary_region = "sin"

[build]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
  source = "data"
  destination = "/app/data"
